### ISSUE TITLE
compose file is not support with 1.9

### ISSUE THREAD

**Issue by elcolie** [py-pa/django-minio-storage#10]
I can not bring up your image and your dockerfile does not mention anythin on `export`
Am I miss something?

```
$ docker info
Containers: 53
 Running: 6
 Paused: 0
 Stopped: 47
Images: 544
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 602
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 4CKI:3OK6:CB3O:VLCE:WARA:YJWA:WCUM:4XZF:ESGR:6LZ5:5BED:H5NM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 53
 Goroutines: 78
 System Time: 2016-11-18T11:16:22.527800156Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: tiras
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

My compose
```
$ docker-compose -version
docker-compose version 1.9.0-rc4, build 181a4e9
```

Your compose file
```  
minio:
    image: "minio/minio"
    command: /export
    environment:
        MINIO_ACCESS_KEY: key2000
        MINIO_SECRET_KEY: secret2000
    ports:
        - "9000:9000"
```

**My problem:**

```
Recreating uihportal_minio_1
Attaching to uihportal_minio_1
minio_1          | minio: <ERROR> ‘/export’ is not a minio sub-command. See ‘minio --help’.
uihportal_minio_1 exited with code 1
```
